print ("how do kangaroo's get better")
input()
print("they have a hop-eration")
input("-----------------------")
print("knock knock")
input("who's there")
print("kanga")
input("kanga who")
print("actually, it's kangaroo")
input("-----------------------")
print("can a kangaroo jump higher than a house?")
input()
print("yes, because houses can't jump")
input("------------------------------")
print("australia")