name = input("hi, what is your name?")
print(f"so,{name}")
print("we are going to play a game")
print("you anwser my questions")
print("and when we are done")
print("we will have a story")
input(r"ready? press enter. (make sure to put a space before your answer)")
animal = input("Name me an animal")
movement = input("name a motion that ends with ed")
vegetable = input("Name a vegetable")
fruit = input("now name a fruit")
store = input("name a grocery store")
number1 = input("name a random number")
number2 = input("name a random number again")
store2 = input("name another store")
place = input(r"Now finally name a area of seattle(capital hill, ballard, magnolia, etc.)")
print("<><><><><<><><><><><><><><><><><>")
print(f"The{animal}{movement} over to the{store2}")
print(f"and saw nothing {name} would like so he went to{store}")
print(f"and bought{number1}{vegetable}s and{number2}{fruit}s")
print(f"then he went to{place} and gave the{number2}{fruit}s to {name}")